app = "sigillaunch"
primary_region = "iad"

[build]
  dockerfile = "Dockerfile"

  [build.args]
    NEXT_PUBLIC_API_BASE = "https://sigil-api.fly.dev"
    NEXT_PUBLIC_ROBINHOOD_RPC_URL = "https://robinhood-mainnet.g.alchemy.com/v2/alch_mkS7FTQnzPCIou3V7eI3c"
    NEXT_PUBLIC_WETH = "0x0Bd7D308f8E1639FAb988df18A8011f41EAcAD73"
    NEXT_PUBLIC_BURN_REGISTRY = "0xe8e62d05f51937647698658f03dfca7e246a43a1"
    NEXT_PUBLIC_CERTIFICATE = "0x97d3caec8e581e95d6b1b15e1ead77cd6fac20bc"
    NEXT_PUBLIC_LAUNCHPAD = "0x86c16a2b955be9c779f2691482d3a9af52089a73"
    NEXT_PUBLIC_VAULT = "0xef611f115764182a318a0dd22e3d4ea4ea4cea87"
    NEXT_PUBLIC_DIVIDEND_ROUTER = "0xdef6ccaa27b736aea644f2d6069b1fdae34ad302"
    NEXT_PUBLIC_SIGIL_TOKEN = "0xfb14980438acc1cdfc45f7de6420c27ef4cc846f"
    NEXT_PUBLIC_EXPLORER_BASE = "https://explorer.robinhood.com"
    NEXT_PUBLIC_WC_PROJECT_ID = "sigil-dev"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

  [http_service.concurrency]
    type = "requests"
    hard_limit = 250
    soft_limit = 200

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512

[env]
  NEXT_PUBLIC_API_BASE = "https://sigil-api.fly.dev"
  NEXT_PUBLIC_ROBINHOOD_RPC_URL = "https://robinhood-mainnet.g.alchemy.com/v2/alch_mkS7FTQnzPCIou3V7eI3c"
  NEXT_PUBLIC_weth = "0x0Bd7D308f8E1639FAb988df18A8011f41EAcAD73"
  NEXT_PUBLIC_BURN_REGISTRY = "0xe8e62d05f51937647698658f03dfca7e246a43a1"
  NEXT_PUBLIC_CERTIFICATE = "0x97d3caec8e581e95d6b1b15e1ead77cd6fac20bc"
  NEXT_PUBLIC_LAUNCHPAD = "0x86c16a2b955be9c779f2691482d3a9af52089a73"
  NEXT_PUBLIC_VAULT = "0xef611f115764182a318a0dd22e3d4ea4ea4cea87"
  NEXT_PUBLIC_DIVIDEND_ROUTER = "0xdef6ccaa27b736aea644f2d6069b1fdae34ad302"
  NEXT_PUBLIC_SIGIL_TOKEN = "0xfb14980438acc1cdfc45f7de6420c27ef4cc846f"
  NEXT_PUBLIC_EXPLORER_BASE = "https://explorer.robinhood.com"
  NEXT_PUBLIC_WC_PROJECT_ID = "sigil-dev"
